// Generated from COMMON_EDITOR_ICONS — do not edit by hand.
import {
  mdiAccount,
  mdiAccountMultiple,
  mdiAirConditioner,
  mdiAlarmLight,
  mdiBed,
  mdiBell,
  mdiBellOutline,
  mdiBlinds,
  mdiCalendar,
  mdiCamera,
  mdiCar,
  mdiCheck,
  mdiClockOutline,
  mdiClose,
  mdiCog,
  mdiCogOutline,
  mdiContentCopy,
  mdiCurtains,
  mdiDelete,
  mdiDoor,
  mdiDoorOpen,
  mdiEmail,
  mdiFan,
  mdiFire,
  mdiFlash,
  mdiFlashOutline,
  mdiFridge,
  mdiGarage,
  mdiGestureTapButton,
  mdiHeart,
  mdiHeartOutline,
  mdiHome,
  mdiHomeOutline,
  mdiInformationOutline,
  mdiLeaf,
  mdiLightbulb,
  mdiLightbulbOff,
  mdiLightbulbOn,
  mdiLightbulbOutline,
  mdiLock,
  mdiLockOpen,
  mdiMapMarker,
  mdiMinus,
  mdiMotionSensor,
  mdiNavigation,
  mdiPause,
  mdiPencil,
  mdiPhone,
  mdiPlay,
  mdiPlus,
  mdiPower,
  mdiRefresh,
  mdiRouterWireless,
  mdiScriptText,
  mdiShieldHome,
  mdiSofa,
  mdiSpeaker,
  mdiStar,
  mdiStarOutline,
  mdiStop,
  mdiTelevision,
  mdiThermometer,
  mdiTimer,
  mdiToggleSwitch,
  mdiToggleSwitchOff,
  mdiWashingMachine,
  mdiWater,
  mdiWaterPercent,
  mdiWeatherNight,
  mdiWeatherSunny,
  mdiWindowOpen,
} from '@mdi/js';

const MDI_PATHS: Record<string, string> = {
  'mdi:account': mdiAccount,
  'mdi:account-multiple': mdiAccountMultiple,
  'mdi:air-conditioner': mdiAirConditioner,
  'mdi:alarm-light': mdiAlarmLight,
  'mdi:bed': mdiBed,
  'mdi:bell': mdiBell,
  'mdi:bell-outline': mdiBellOutline,
  'mdi:blinds': mdiBlinds,
  'mdi:calendar': mdiCalendar,
  'mdi:camera': mdiCamera,
  'mdi:car': mdiCar,
  'mdi:check': mdiCheck,
  'mdi:clock-outline': mdiClockOutline,
  'mdi:close': mdiClose,
  'mdi:cog': mdiCog,
  'mdi:cog-outline': mdiCogOutline,
  'mdi:content-copy': mdiContentCopy,
  'mdi:curtains': mdiCurtains,
  'mdi:delete': mdiDelete,
  'mdi:door': mdiDoor,
  'mdi:door-open': mdiDoorOpen,
  'mdi:email': mdiEmail,
  'mdi:fan': mdiFan,
  'mdi:fire': mdiFire,
  'mdi:flash': mdiFlash,
  'mdi:flash-outline': mdiFlashOutline,
  'mdi:fridge': mdiFridge,
  'mdi:garage': mdiGarage,
  'mdi:gesture-tap-button': mdiGestureTapButton,
  'mdi:heart': mdiHeart,
  'mdi:heart-outline': mdiHeartOutline,
  'mdi:home': mdiHome,
  'mdi:home-outline': mdiHomeOutline,
  'mdi:information-outline': mdiInformationOutline,
  'mdi:leaf': mdiLeaf,
  'mdi:lightbulb': mdiLightbulb,
  'mdi:lightbulb-off': mdiLightbulbOff,
  'mdi:lightbulb-on': mdiLightbulbOn,
  'mdi:lightbulb-outline': mdiLightbulbOutline,
  'mdi:lock': mdiLock,
  'mdi:lock-open': mdiLockOpen,
  'mdi:map-marker': mdiMapMarker,
  'mdi:minus': mdiMinus,
  'mdi:motion-sensor': mdiMotionSensor,
  'mdi:navigation': mdiNavigation,
  'mdi:pause': mdiPause,
  'mdi:pencil': mdiPencil,
  'mdi:phone': mdiPhone,
  'mdi:play': mdiPlay,
  'mdi:plus': mdiPlus,
  'mdi:power': mdiPower,
  'mdi:refresh': mdiRefresh,
  'mdi:router-wireless': mdiRouterWireless,
  'mdi:script-text': mdiScriptText,
  'mdi:shield-home': mdiShieldHome,
  'mdi:sofa': mdiSofa,
  'mdi:speaker': mdiSpeaker,
  'mdi:star': mdiStar,
  'mdi:star-outline': mdiStarOutline,
  'mdi:stop': mdiStop,
  'mdi:television': mdiTelevision,
  'mdi:thermometer': mdiThermometer,
  'mdi:timer': mdiTimer,
  'mdi:toggle-switch': mdiToggleSwitch,
  'mdi:toggle-switch-off': mdiToggleSwitchOff,
  'mdi:washing-machine': mdiWashingMachine,
  'mdi:water': mdiWater,
  'mdi:water-percent': mdiWaterPercent,
  'mdi:weather-night': mdiWeatherNight,
  'mdi:weather-sunny': mdiWeatherSunny,
  'mdi:window-open': mdiWindowOpen,
};

const MDI_FALLBACK_PATH =
  'M11,18H13V16H11V18M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,6A4,4 0 0,0 8,10H10A2,2 0 0,1 12,8A2,2 0 0,1 14,10C14,12 11,11.75 11,15H13C13,12.75 16,12.5 16,10A4,4 0 0,0 12,6Z';

export function getMdiPath(icon: string): string {
  return MDI_PATHS[icon] ?? MDI_FALLBACK_PATH;
}
